export const ADDCART = "ADDCART";
export const ADDCART_SUCCESS = "ADDCART_SUCCESS";

export const LOGIN_DATA = "LOGIN_DATA";
export const LOGIN_DATA_SUCCESS = "LOGIN_DATA_SUCCESS";

export const FEATCHCART = "FEATCHCART";
export const FEATCHCART_SUCCESS = "FEATCHCART_SUCCESS";

export const DELETECART = "DELETECART";
export const DELETECART_SUCCESS = "DELETECART_SUCCESS";

export const UPDATECART = "UPDATECART";
export const UPDATECART_SUCCESS = "UPDATECART_SUCCESS";